image:
#- Visual Studio 2017 # how to setup ssl-dev etc.
- Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 3

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- sh: export GEM_HOME=$HOME/gems
- sh: export PATH=$HOME/gems/bin:$PATH
- sh: sudo apt -yq update > /dev/null
- sh: sudo apt install -yq --no-install-suggests --no-install-recommends libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev > /dev/null

install:
- gem install github-linguist --no-document
- pip install -e .[tests]

test_script: pytest -rsv

