language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: GEM_HOME=$HOME/gems PATH=$HOME/gems/bin:$PATH

addons:
  apt:
    packages:
    - ruby-dev
    - libssl-dev

matrix:
  include:
  - os: linux
    python: 3.6
    after_success:
    - pytest --cov
    - coveralls
  - os: linux
    python: 3.7
    install:
    - pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .


install:
- gem install github-linguist --no-document
- pip install -e .[tests]

script:
- pytest -rsv