language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: GEM_HOME=$HOME/gems PATH=$HOME/gems/bin:$PATH

addons:
  apt:
    packages:
    - ruby-dev
    - libssl-dev

before_install: gem install github-linguist --no-document

matrix:
  include:
  - os: linux
    name: Integration install
    python: 3.7
    install:
    - python setup.py install
    - pip install ghlinguist[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests -r a -v
  - os: linux
    name: PEP8 MyPy
    python: 3.7
    install:
    - pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .


install: pip install -e .[tests]

script: pytest -r a -v
