name: ci

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: gem install github-linguist --no-document
    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest
