name: ci

on:
  push:
    files:
      - '**.py'
      - '.github/workflows/ci.yml'

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - uses: actions/checkout@v3

    - run: gem install github-linguist --no-document

    - run: pip install .[tests,lint]

    - run: flake8

    - run: mypy

    - run: pytest
