name: ci

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -e .[lint]
    - name: Lint
      run: flake8
    - name: Type check
      run: mypy .

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: gem install github-linguist --no-document
    - run: pip install -e .[tests]
    - run: pytest -r a -v

  install:
    needs: [integration]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: sudo apt install libssl-dev ruby-dev
    - run: gem install github-linguist --no-document
    - run: python setup.py install
    - run: |
        cd ${HOME}
        python -m pip install pytest
        python -m pytest ${GITHUB_WORKSPACE} -r a -v
